### ISSUE TITLE
Name of the input file should be input.xyz, orca.xyz isn't working

### ISSUE THREAD

**Issue by lastcall3** [PodewitzLab/PyConSolv#19]
could not back up original file
Traceback (most recent call last):
  File "/home/mas/envs/PyConSolv/bin/pyconsolv", line 8, in <module>
    sys.exit(main())
  File "/home/mas/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/pyconsolv.py", line 50, in main
    conf.run(charge= args.charge , method = args.method, basis = args.basis , dsp = args.dispersion , cpu = args.cpu ,
  File "/home/mas/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/ConfGen.py", line 678, in run
    self.setup(charge, method, basis, dsp, solvent, cpu, multiplicity)
  File "/home/mas/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/ConfGen.py", line 262, in setup
    self.xyz.prepareInput(self.inputpath + '/input.xyz')
  File "/home/mas/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/misc/inputparser.py", line 709, in prepareInput
    self.readXYZ(inputfile)
  File "/home/mas/envs/PyConSolv/lib/python3.10/site-packages/PyConSolv/misc/inputparser.py", line 96, in readXYZ
    f = open(path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/mas/Mocat/MoCat4/MD/input.xyz'

**Comment by Lapsis-glitch** [comment]
solved with merge #22
