### ISSUE TITLE
Issue when trying to use counterions

### ISSUE THREAD

**Issue by Lapsis-glitch** [PodewitzLab/PyConSolv#30]
You system is charged, would you like to select an appropriate counterion?
 y/n: y
Please choose one of the following counterions:

OTf-, BF4-, BARF-, PFC-, ScF6-, ClO4-, BPh4-, custom

custom
You have chosen a custom counterion for your system, which needs to be parametrized
Please provide a path to the location of an XYZ file containing your ion

/home/rat/PYCONSOLV_DATA/issue_CTI/CTI/input.xyz
Please enter the charge for your ion:
2
Traceback (most recent call last):
  File "/home/rat/PycharmProjects/pyconsolv.py", line 57, in <module>
    main()
  File "/home/rat/PycharmProjects/pyconsolv.py", line 52, in main
    conf.run(charge= args.charge , method = args.method, basis = args.basis , dsp = args.dispersion , cpu = args.cpu ,
  File "/home/rat/PycharmProjects/PyConSolv/src/PyConSolv/ConfGen.py", line 741, in run
    self.setup(charge, method, basis, dsp, solvent, cpu, multiplicity)
  File "/home/rat/PycharmProjects/PyConSolv/src/PyConSolv/ConfGen.py", line 274, in setup
    self.prepareCounterion(method, basis, dsp, cpu, charge, cpcm)
  File "/home/rat/PycharmProjects/PyConSolv/src/PyConSolv/ConfGen.py", line 246, in prepareCounterion
    cIon.run(method, basis, dsp, cpu, cpcm, int(chargeIon))
  File "/home/rat/PycharmProjects/PyConSolv/src/PyConSolv/misc/parametrizerInterface.py", line 204, in run
    self.parseXYZ()
  File "/home/rat/PycharmProjects/PyConSolv/src/PyConSolv/misc/parametrizerInterface.py", line 75, in parseXYZ
    self.solventmol2 = np.array(self.xyz.ligands)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by Lapsis-glitch** [comment]
This is caused when using single atoms as counterions.

**Comment by Lapsis-glitch** [comment]
Fixed with 47ca1120a8af5699965572dfdcbc96317deae4df and 7bc4b1ce7a97546480d85a028baf271344e10c02

Single atom counterions not directly supported still present an issue. Although unlikely, if a very specific atom is needed as a counterion, parameters have to be manually created and added to the LIG_tleap file. If there is enough demand for this, it could be implemented as a feature in the future.
