### ISSUE TITLE
Cluster analysis leads to an error

### ISSUE THREAD

**Issue by maberl1** [PodewitzLab/PyConSolv#70]
Oy,
Calling "pyconsolv sim-01 -a" on a simulation set up with PyConSolv leads to the following error, right after the last single point calculation and the creation of cluster_ranking.dat which contains all the SP energies for the cluster reps. Posting the whole dialogue:

> pyconsolv sim-01 -a -mask 4,5,6,8,9 -cluster kmeans

clustering using kmeans

Please enter the number of desired clusters: (default 10)
10
Please enter the value for the frame number sieve: (default 10)
10
Clustering done!

Found ORCA in [ORCA path]
Running calculation for rep.c1.pdb
Running calculation for rep.c6.pdb
Running calculation for rep.c8.pdb
Running calculation for rep.c9.pdb
Running calculation for rep.c7.pdb
Running calculation for rep.c0.pdb
Running calculation for rep.c3.pdb
Running calculation for rep.c4.pdb
Running calculation for rep.c5.pdb
Running calculation for rep.c2.pdb
Traceback (most recent call last):
  File "[path of conda env]/bin/pyconsolv", line 8, in <module>
    sys.exit(main())
  File "[path of conda env]/lib/python3.10/site-packages/PyConSolv/pyconsolv.py", line 70, in main
    analysis.run(clustering=cluster, nosp=args.nosp, engine=args.engine, qmmm=args.qmmm)
  File "[path of conda env]/lib/python3.10/site-packages/PyConSolv/misc/analysis.py", line 471, in run
    if opt:
UnboundLocalError: local variable 'opt' referenced before assignment

Thanks <3

**Comment by Lapsis-glitch** [comment]
fixed with https://github.com/PodewitzLab/PyConSolv/commit/d3542e2ed41fbdd4fc3f5b8f5eb1c278cc35d552
