### ISSUE TITLE
Issue with restraining multiple non-covalently bound fragments

### ISSUE THREAD

**Issue by Lapsis-glitch** [PodewitzLab/PyConSolv#72]
Restraining ids all to cartesian coordinates with the strength of 100
Traceback (most recent call last):
  File "/home/krs/.conda/envs/pcs_1.0.6.3.1/bin/pyconsolv", line 8, in <module>
    sys.exit(main())
  File "/home/krs/.conda/envs/pcs_1.0.6.3.1/lib/python3.10/site-packages/PyConSolv/pyconsolv.py", line 78, in main
    conf.run(charge=args.charge, method=args.method, basis=args.basis, dsp=args.dispersion, cpu=args.cpu,
  File "/home/krs/.conda/envs/pcs_1.0.6.3.1/lib/python3.10/site-packages/PyConSolv/ConfGen.py", line 1000, in run
    if self.equilibration(cpu, engine, cart=cart, cartstr = cartstr) == 0:
  File "/home/krs/.conda/envs/pcs_1.0.6.3.1/lib/python3.10/site-packages/PyConSolv/ConfGen.py", line 691, in equilibration
    cart = '1-{}'.format(len(self.xyz.files))
TypeError: object of type 'NoneType' has no len()

**Comment by Lapsis-glitch** [comment]
Can be fixed by changing line 691 in ConfGen.py by setting self.xyz.files to self.xyz.filenames

**Comment by Lapsis-glitch** [comment]
fixed with https://github.com/PodewitzLab/PyConSolv/commit/e4dfe6c9f6bc904bedbe74709320406573db71dc
